### ISSUE TITLE
Exception expiring tiles

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/chef#213]
Trying to catch up yevaud I'm seeing some of the downloaded changes causing an exception at https://github.com/openstreetmap/chef/blob/9d133ea818fd0c49da38bdb756e139060aee5390/cookbooks/tile/files/default/bin/expire-tiles-single#L55 when expiring tiles:

```
Traceback (most recent call last):
  File "/usr/local/bin/expire-tiles-single", line 141, in <module>
    expire_meta_tiles(options)
  File "/usr/local/bin/expire-tiles-single", line 91, in expire_meta_tiles
    proc.apply_file(options.inputfile)
  File "/usr/local/bin/expire-tiles-single", line 55, in way
    except o.NotFoundError:
AttributeError: 'module' object has no attribute 'NotFoundError'
```

**Comment by tomhughes** [comment]
Looks like `NotFoundError` was removed from pyosmium in https://github.com/osmcode/pyosmium/commit/ab571063c8d8bcd055b140409f9f3cec38023e88.

**Comment by tomhughes** [comment]
I think it's called `OsmiumKeyError` now?
